@startuml diagrama

entity "Cliente" as eCliente{
    id: long <<generated>>
    --

    nombre 
    telefone
    email
    
}

entity "Direccion" as eDireccion{
    id: long <<generated>>
    --
    Provincia
    Municipio
    Calle
    Numero
    id_cliente:FK
}


entity "Receptor" as eReceptor{
    id: long <<generated>>
    --
    longitud
    latitud
    altura
    id_repetidor:FK
    id_servicioPrestado:FK
}

entity "Repetidor" as eRepetidor{
    id: long <<generated>>
    --
    nombre
    direccionFisica
    radioAlcance
    cantidadMaximaConexiones
    longitud
    latitud
}

entity "ServicioPrestado"  as eServicioPrestado{
    id: long <<generated>>
    --
    id_servicio:FK     
    costoVariable: Long ?????
    Coeficiente: Double
    RecargoDistancia: Double
    RecargoAltura: Double
    id_cliente:FK
    id_direccion:FK
    
}

entity "Servicio" as eServicio{
    id: long <<generated>>
    --
    precioBase: Int
    cantidadMB: Int 
   
}

entity "tarifaInstalacion" as eTarifaInstalacion{
    id: long <<generated>>
    --
    fecha: Date
    costoInstalacion: Double
    id_servicio:FK
}

entity "Presupuesto" as ePresupuesto{
    id: long <<generated>>
    --
    fecha: Date
    id_servicioPrestado:FK
    id_cliente:FK
    id_tarifaInstalacion: FK
}

entity "Estado" as eEstado{
    id: long <<generated>>
    --
    idPresupuesto: FK
    fecha: Date
    estadoPosible: varChar
}


ePresupuesto }|-|| eTarifaInstalacion
eServicioPrestado }|-||eServicio
eReceptor }o-|| eRepetidor
eTarifaInstalacion }o--|| eServicio
eCliente ||--o{ eServicioPrestado
eCliente ||--o{ ePresupuesto
eServicioPrestado ||--|| eDireccion
eServicioPrestado ||--o| eReceptor 
ePresupuesto ||--|{ eEstado


@enduml
